### ISSUE TITLE
Battery duration

### ISSUE THREAD

**Issue by HerrAugust** [Open-Smartwatch/open-smartwatch.github.io#15]
Hello, I bought the smartwatch light version (without GPS) and I will use one of the two batteries:

1. https://es.aliexpress.com/item/4000293204820.html
2. https://a.aliexpress.com/_mrvOz8P

Can anyone tell me about the estimated battery duration when the smartwatch has:

1. screen always turned off (or turned on only for a new notification)
2. BLE connected all the day to an Android v8 smartphone (to received message and email notifications)
3. WiFi always turned off

Thank you a lot!

**Comment by uvwxy** [comment]
@simonmicro I had to enable issues on the docs/website repo.

**Comment by uvwxy** [comment]
Back to topic:

As notifications are not implemented, this specific use case has no data... yet ?

**Comment by simonmicro** [comment]
@uvwxy Oh, my bad.

> As notifications are not implemented, this specific use case has no data... yet ?

This specific use case has no data yet.

Whenever we implement that, we should add it then......

**Comment by HerrAugust** [comment]
Thank you for reply! So there is no available estimation for my use case? If this is the case, how long does the smartwatch last normally in your everyday usage ( and under which conditions do you use it )?

**Comment by simonmicro** [comment]
Hmm - I have multiple ones. They both work for about 2-4 days with Light Sleep and WiFi (on boot) enabled. Shame on me I if recall those incorrectly.
