### ISSUE TITLE
Document available `OSW_FEATURE_`-flags

### ISSUE THREAD

**Issue by simonmicro** [Open-Smartwatch/open-smartwatch.github.io#20]
As requested in https://github.com/Open-Smartwatch/open-smartwatch-os/issues/98 we should document what feature flags are available to control which part of the OS. For that we should create a new page in the docs and note them down with a short description.

**Comment by RuffaloLavoisier** [comment]
@simonmicro 
We need to check if it's a similar page or if it already exists

Repo : https://github.com/Open-Smartwatch/open-smartwatch.github.io/blob/source/docs/resources/firmware.md

Site : https://open-smartwatch.github.io/resources/firmware/

**Comment by simonmicro** [comment]
Oh, good catch! I have completely forgotten that page! We should extend it then...

**Comment by uvwxy** [comment]
The only define/flag that is not mentioned in the `firmware.md` file is `OSW_FEATURE_BLE_MEDIA_CTRL`. As this is a tech demo and not a feature itself I don't see we need to add this to the docs.
